{"level":40,"time":1641609610555,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-10","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdBoard (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\boards\\board.router.ts:36:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
{"level":40,"time":1641609610608,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-1d","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdTask (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\tasks\\task.router.ts:42:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
{"level":40,"time":1641609610611,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-1e","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdTask (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\tasks\\task.router.ts:42:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
{"level":40,"time":1641609610611,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-1f","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdTask (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\tasks\\task.router.ts:42:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
{"level":40,"time":1641609610613,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-1g","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdTask (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\tasks\\task.router.ts:42:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
{"level":40,"time":1641609610615,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-1h","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdTask (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\tasks\\task.router.ts:42:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
{"level":40,"time":1641609611010,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-1v","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdTask (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\tasks\\task.router.ts:42:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
{"level":40,"time":1641609645756,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-2v","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdBoard (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\boards\\board.router.ts:36:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
{"level":40,"time":1641609645812,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-38","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdTask (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\tasks\\task.router.ts:42:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
{"level":40,"time":1641609645813,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-39","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdTask (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\tasks\\task.router.ts:42:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
{"level":40,"time":1641609645814,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-3a","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdTask (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\tasks\\task.router.ts:42:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
{"level":40,"time":1641609645815,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-3b","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdTask (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\tasks\\task.router.ts:42:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
{"level":40,"time":1641609645816,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-3c","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdTask (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\tasks\\task.router.ts:42:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
{"level":40,"time":1641609646220,"pid":19080,"hostname":"DESKTOP-KQBTM56","reqId":"req-3q","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\reply.js:124:26)\n    at Object.getIdTask (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\src\\resources\\tasks\\task.router.ts:42:7)\n    at preHandlerCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:72:7)\n    at handleRequest (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\handleRequest.js:20:5)\n    at runPreParsing (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:427:5)\n    at Object.routeHandler [as handler] (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\fastify\\lib\\route.js:385:7)\n    at Router.lookup (C:\\Users\\Signum\\Desktop\\nodejs2021Q4-service-dev\\node_modules\\find-my-way\\index.js:378:14)\n    at Server.emit (node:events:390:28)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
